package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os/exec"
)

func main() {
	getDriveInfo()
}

func getDriveInfo() {
	out, err := exec.Command("lsblk", "-J", "-a").Output()
	if err != nil {
		log.Fatal(err)
	}
	str := string(out)
	fmt.Println(str)
	type AutoGenerated struct {
		Blockdevices []struct {
			Name       string `json:"name"`
			MajMin     string `json:"maj:min"`
			Rm         string `json:"rm"`
			Size       string `json:"size"`
			Ro         string `json:"ro"`
			Type       string `json:"type"`
			Mountpoint string `json:"mountpoint"`
			Children   []struct {
				Name       string `json:"name"`
				MajMin     string `json:"maj:min"`
				Rm         string `json:"rm"`
				Size       string `json:"size"`
				Ro         string `json:"ro"`
				Type       string `json:"type"`
				Mountpoint string `json:"mountpoint"`
			} `json:"children,omitempty"`
		} `json:"blockdevices"`
	}
	bytes, err := json.Marshal(str)
	if err != nil {
		fmt.Println(err)
	}
	var d AutoGenerated
	err = json.Unmarshal(bytes, &d.Blockdevices)

	fmt.Printf("%+v\n", d)
}
